apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
  capacity:
    storage: 2Gi
  nfs:
    server: 192.168.1.10
    path: "/data"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
  capacity:
    storage: 2Gi
  nfs:
    server: 192.168.1.10
    path: "/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-mysql-claim
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-wp-claim
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
